# Generated by Django 5.2.10 on 2026-01-18 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropOffLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dropoff Location',
                'verbose_name_plural': 'Dropoff Locations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickUpLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pickup Location',
                'verbose_name_plural': 'Pickup Locations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NavigationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('state', models.CharField(choices=[('no_selection', 'No Selection'), ('pickup_selected', 'Pickup Selected'), ('navigated_to_pickup', 'Navigated to Pickup'), ('dropoff_selected', 'Dropoff Selected'), ('navigated_to_dropoff', 'Navigated to Dropoff'), ('completed', 'Completed')], default='no_selection', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dropoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.dropofflocation')),
                ('pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.pickuplocation')),
            ],
            options={
                'verbose_name': 'Navigation Session',
                'verbose_name_plural': 'Navigation Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
